### ISSUE TITLE
Audio_emo_label

### ISSUE THREAD

**Issue by wzx7084** [wuhaozhe/4d_reconstruction#1]
Thank you very much for doing such a good job. I am very interested in your work. Regarding the MMFACE4D dataset mentioned in your paper, you can see that there are emotional labels for speech. But I couldn't find any label information about emotions in the data set I retrieved. Ask me how I can get these emotional labels. Looking forward to your reply!

**Comment by wuhaozhe** [comment]
neutral sentence has prefix 00, happy sentence has prefix 21, angry sentence has prefix 22, sad sentence has prefix 23, surprise sentence has prefix 24, fear sentence has prefix 25, disgust sentence has prefix 26.
